server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group # 定义事务组的名称

seata:
  enabled: true
  config:
    registry:
      type: nacos
      nacos:
        server-addr: 127.0.0.1:8848
        group: "DEFAULT_GROUP"
        namespace: "public" # TODO seata_test
        username: "nacos"
        password: "nacos"
        cluster: default
        data-id: "seata-registry-default.conf"
    config:
      type: nacos
      nacos:
        namespace: "public" # TODO seata_test
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        username: "nacos"
        password: "nacos"
        dataId: "seata-config-default.conf"

mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug

ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

